version: 2

python:
  version: 3.8
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
  system_packages: true

sphinx:
  configuration: source/conf.py

formats: all

